//tealium universal tag - utag.495 ut4.0.201706262146, Copyright 2017 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={"id":id};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
if(utag.ut.loader===undefined){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id};if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=utag.ut.loader;}
u.encode=function(a,b){b="";try{b=encodeURIComponent(a)}catch(e){utag.DB(e);}if(b==""){b=escape(a);}return b}
u.ev={"view":1};u.rp=function(a,b){if(typeof a!=="undefined"&&a.indexOf("@@")>0){a=a.replace(/@@([^@]+)@@/g,function(m,d){if(b[d]){return u.encode(b[d]);}else{return"";}});}
return a;};u.map={"zz_look_action2id":"ev","zz_generic_id":"cd[suggested_hotels]","zz_generic_id2":"cd[content_ids]","action":"cd[action]","dest_ufi":"cd[destination_ids]","user_location":"cd[user_cc1]","currency":"cd[purchase_currency]","ttv_uc":"cd[purchase_value]","date_in":"cd[checkin_date]","date_out":"cd[checkout_date]","rooms":"cd[rooms]","nights":"cd[nights]","hr":"cd[hotel_rank]","rid":"cd[order_id]","p1":"cd[value]","adults":"cd[num_adults]","children":"cd[num_children]","city_name":"cd[city]","country_name":"cd[country]","dest_name":"cd[destination]","region_name":"cd[region]","ai":"cd[aid]","preferred_neighborhoods":"cd[preferred_neighborhoods]","preferred_star_ratings":"cd[preferred_star_ratings]","seed":"cd[val1]","site":"cd[site]","sid":"cd[val2]","channel_id":"cd[val3]"};u.extend=[function(a,b,c,d,e,f,g){d=b['action'];if(typeof d=='undefined')return;c=[{'searchresults':'Search'},{'hotel':'ViewContent'},{'book':'InitiateCheckout'},{'confirmation':'Purchase'},{'myreservations':'Purchase'}];var m=false;for(e=0;e<c.length;e++){for(f in c[e]){if(d==f){b['zz_look_action2id']=c[e][f];m=true};};if(m)break};if(!m)b['zz_look_action2id']='PageView';},function(a,b){if(b.children&&b.children<0){b.children=undefined;}
if(b.adults&&b.adults<0){b.adults=undefined;}
if(b.region_name&&b.region_name=='-1'){b.region_name=undefined;}
if(b.dest_ufi&&b.dest_ufi=='-1'){b.dest_ufi=undefined;}
if(b.date_in&&b.date_in=='-1'){b.date_in=undefined;}
if(b.date_out&&b.date_out=='-1'){b.date_out=undefined;}
if(b.rooms&&b.rooms=='-1'){b.rooms=undefined;}
if(b.nights&&b.nights=='-1'){b.nights=undefined;}
if(b.hr&&b.hr=='-1'){b.hr=undefined;}
if(b.city_name&&b.city_name=='-1'){b.city_name=undefined;}
if(b.country_name&&b.country_name=='-1'){b.country_name=undefined;}
if(b.dest_name&&b.dest_name=='-1'){b.dest_name=undefined;}
var hotel_id=b.hotel_id&&b.hotel_id>0?b.hotel_id:undefined;var hotel_id_list=b.hotel_id_list;if(!hotel_id_list){hotel_id_list=hotel_id;}else{var hotel_id_list_raw=hotel_id_list.split(",");hotel_id_list=[];for(var i=0;i<hotel_id_list_raw.length;i++){var id=parseInt(hotel_id_list_raw[i].trim(),10);if(!isNaN(id)){hotel_id_list.push(id);}}
hotel_id_list=JSON.stringify(hotel_id_list);}
if(b.action==='searchresults'){b.zz_generic_id=hotel_id_list;b.zz_generic_id2=hotel_id_list;}else{b.zz_generic_id=hotel_id_list;b.zz_generic_id2=hotel_id;}
var preferred_neighborhoods=b.district_name&&b.district_name!='-1'?[b.district_name]:b.preferred_neighborhoods;if(preferred_neighborhoods){b.preferred_neighborhoods=JSON.stringify(preferred_neighborhoods);}
if(b.preferred_star_ratings){b.preferred_star_ratings=JSON.stringify(b.preferred_star_ratings);}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f;u.data={"qsp_delim":"&","kvp_delim":"=","qs_delim":"?","tag_type":"img","base_url":"https://www.facebook.com/tr","secure_base_url":"","static_params":"id=405133399621612&cd[content_type]=hotel&cd[currency]=EUR&noscript=1","cachebust":"disabled","cachevar":""||"_rnd"};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){if(typeof utag_err!='undefined'){utag_err.push({e:'extension error:'+e,s:utag.cfg.path+'utag.'+id+'.js',l:c,t:'ex'})}}};utag.DB("send:495:EXTENSIONS");utag.DB(b);c=[];for(d in utag.loader.GV(u.map)){if(typeof b[d]!=="undefined"&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){if(!u.data.hasOwnProperty(e[f])){c.push(e[f]+"##kvp_delim##"+u.encode(b[d]));}
u.data[e[f]]=b[d];}}}
u.data.secure_base_url=u.data.secure_base_url||u.data.base_url;u.data.url=(location.protocol==="https:"?u.data.secure_base_url:u.data.base_url);if(u.data.url.indexOf("http")!==0&&u.data.url.indexOf("/")!==0){u.data.url=location.protocol+"//"+u.data.url;}
if(u.data.static_params){c.push(u.data.static_params);}
var cb_check=new RegExp("(\\"+u.data.qs_delim+"|"+u.data.qsp_delim+")"+u.data.cachevar+"=");if(u.data.cachebust==="enabled"&&!cb_check.test(u.data.url)){c.push([u.data.cachevar,Math.random()].join(u.data.kvp_delim));}
if(c.length>0){if(u.data.url.indexOf(u.data.qs_delim)<0){u.data.url+=u.data.qs_delim;}else if(u.data.url.indexOf(u.data.qs_delim)!==(u.data.url.length-1)){u.data.url+=u.data.qsp_delim;}}
u.data.url=u.rp(u.data.url,b)+c.join(u.data.qsp_delim);u.data.url=u.data.url.replace(/##kvp_delim##/g,u.data.kvp_delim);u.loader({"type":u.data.tag_type,"src":u.data.url,"loc":"script","id":"utag_495"});utag.DB("send:495:COMPLETE");}};utag.o[loader].loader.LOAD(id);}("495","booking.com.main"));}catch(error){utag.DB(error);}
